#!/usr/bin/python3

def raise_exception():
    a = 1
    b = 'str'
    c = a + b
    print(c)
